SystemOrganization addCategory: #LiveInstanceVisualization!
SystemOrganization addCategory: 'LiveInstanceVisualization-Debugger'!
SystemOrganization addCategory: 'LiveInstanceVisualization-Diff'!
SystemOrganization addCategory: 'LiveInstanceVisualization-Inspector-Extensions'!
SystemOrganization addCategory: 'LiveInstanceVisualization-Models'!
SystemOrganization addCategory: 'LiveInstanceVisualization-Tests'!
